% New Developments in Academic Activities
% Robert M Flight
% 05/12/12

```{r knitrSetup, include=FALSE}
#opts_chunk$set(cache=TRUE)
knit_hooks$set(error = function(x, options) stop(x)) 
```

# Activities??

 * Communication
 * Academic Impact
 * Publishing and Peer Review
 * Sharing: Data and Code
 * Funding
 

# Communication

 * [Twitter](https://twitter.com/rmflight)
     * 140 character "tweets"
     * follow people of interest
     * people follow you
     * hashtags (#) allow grouping of tweets related to a subject
     * useful to learn of new papers, research in communities of interest
     * tweet your papers when published!

# Academic Impact

 * Name Disambiguation
 * Paper Impact
 * AltMetrics


# Name Disambiguation

 * Who is the author on the paper? Person on the grant?
 * [ORCID](http://orcid.org)
     * unique ID to provide disambiguation for authors
     * supported by publishers, universities, etc
     * [example page](https://orcid.org/0000-0001-8141-7788)
     

# Impact of papers

 * Usually consider **impact factor** of journals, citation counts in literature
 * Outside of tenure & promotion committees, these specific values become less important
 * [Google Scholar](http://scholar.google.com/citations?user=G8bFNwYAAAAJ&hl=en)


# AltMetrics
 * Alternative ways of considering **[impact](http://altmetrics.org/tools/)**
     * Who is reading; saving; discussing & citing
     * Examples [1](http://impactstory.org/collection/of49tu)  [2](http://impactstory.org/collection/pn6ow0)
   

# Publishing

 * Open Access
 * Peer Review

# Open Access

 * Open access in traditional journals
     * Pay large fees to make available immediately, forever
     * Access for text mining??
 * [PeerJ](http://peerj.org)
     * Pay $99, publish once a year, forever
     * Peer review once a year
     * Biosciences
     * Option to publish reviews
     * Preprint service
 * [eLife](http://www.elifesciences.org/the-journal/)
     * backed by HHMI, Max Planck Society, Wellcome Trust
     * **outstanding** research only
     * full XML available on [Github](https://github.com/elifesciences/elife-articles)
     * currently free to pubish
 
# Peer Review

 * Move to have reviewers sign reviews
 * Including reviews in the publication
 * Arxiv models, but with better outputs (eg html, currently only pdf)
     * submit preprint, get comments, review, then submit
     * Arxiv has section for [Quantitative Biology](http://arxiv.org/list/q-bio/new)
 * [Peerage of Science](http://www.peerageofscience.org/)
     * Review, journals can decide to publish or not
 * [Faculty of 1000](http://f1000.com/prime)
     * Pay small fee per month to get access to recommendations of published literature
     
# Sharing

 * [Figshare](http://figshare.com/)
     * Host and share any type of file, figure, video, etc, and get DOI
     * CC-BY
 * [Dryad](http://datadryad.org/)
     * Specifically for data referenced in journal articles
 * [Run My Code](http://www.runmycode.org/CompanionSite/)
     * Host code for download, or working code from publications
     * If desired, can vary parameters, or use publication data
 * [Github](https://github.com/)
     * host anything you want in version control
     * used to collaboratively work on many things, including publications [1](https://github.com/PhDP/article_preprint/blob/master/ms.tex) [2](https://github.com/cwcon/push) [3](https://github.com/rmflight/affyMM/)
     
# Funding

 * [RocketHub](http://www.rockethub.com/projects/11106-crowdsourcing-discovery)
     * Kickstarter like
     * Propose research, ask for funding, keep funders informed
     
# Acknowledgements

 * @ImpactStory
 * @figshare
 * Heather Piwowar (@researchremix)
 * Carl Boettiger (@cboettig)
 * Kevin Brock (@brockoleur)
 * Jason Priem (@jasonpriem)

# Generate slides

 require(knitr)
 knit("academic_developments.Rmd")
 system("pandoc -s -S -t slidy --slide-level=1 --mathjax academic_developments.md -o academic_developments.html")